### ISSUE TITLE
Nothing happened when using the plugin

### ISSUE THREAD

**Issue by wooshone** [peerjollux/Shrimp-Sketch-Plugin#3]
Hey,

i tryed your plugin. But if i use it, it happens nothing. Just said "Well done! We just optimized 0 images."

**Comment by peerjollux** [comment]
Thanks for your feedback, i can't recreate the problem. Is it possible you send me your test sketch document? @wooshone

**Comment by themanro** [comment]
Does not work. "Well done! We just optimized 0 images” every time.

**Comment by cangoktas** [comment]
indeed, no response from the plugin. I can share you the document I'm trying to use on, can you provide me your mail address @peerjollux?

**Comment by peerjollux** [comment]
Thanks for your comments. This plugin is not maintained & needed anymore. Sketch now (since 3.9) has a build in function to reduce the file size. This function can be found via File>Reduce file size.
